version: '2'
services:
    debattons-app:
        image: debattons
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://debattons-postgresql:5432/Debattons
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    debattons-postgresql:
        extends:
            file: postgresql.yml
            service: debattons-postgresql
